### ISSUE TITLE
作者您好，请教一个数据输入大小的问题

### ISSUE THREAD

**Issue by wzr0108** [windygoo/PromptNucSeg#1]
sam的backbone是vit，会对图片做16倍下采样，256x256的输入会不会太小了。

**Comment by wzr0108** [comment]
如果256x256放大到1024x1024，正好对应sam的输入大小。而且HoverNet的第一层特征图不做下采样，跟输入图片放大4倍应该也是等价的

**Comment by windygoo** [comment]
> sam的backbone是vit，会对图片做16倍下采样，256x256的输入会不会太小了。

我觉得这个得看细胞相对图像的大小吧，单纯看图像分辨率意义不是很大。我在训练中没有直接将高分辨率的图像resize到256，而是用了RandomCrop256的数据增强，这样细胞在图像中的可分辨性维持不变。此外，Pannuke数据集本身的图像大小也就是256。

可能是论文里没说清楚，临近DDL在抓紧改了，过一周多会把最终版本传到arxiv上，代码也会更新。

**Comment by wzr0108** [comment]
谢谢解答，论文里有说RandomCrop256。只是我有个疑问，细胞核都是小目标，很多的长或宽都小于32。很多backbone的第一层特征图是4倍下采样，HoverNet的做法是不做下采样，保证了特征图的有足够的大小。这跟图片放大4倍是等价的，因为模型参数量和计算量都相等的。
而sam的PatchEmbeddings是16倍采样，我担心检测不到小目标

**Comment by windygoo** [comment]
> 谢谢解答，论文里有说RandomCrop256。只是我有个疑问，细胞核都是小目标，很多的长或宽都小于32。很多backbone的第一层特征图是4倍下采样，HoverNet的做法是不做下采样，保证了特征图的有足够的大小。这跟图片放大4倍是等价的，因为模型参数量和计算量都相等的。 而sam的PatchEmbeddings是16倍采样，我担心检测不到小目标

我觉得你的想法挺有道理的，比较偏实验性。或许你可以参考[SAMUS](https://github.com/xianlin7/samus)把patch size改成8，测试一下分割效果有没有变得更好。

**Comment by wzr0108** [comment]
谢谢！
论文里PointNu-Net在CPM-17和kumar的结果是自己跑的实验吗

**Comment by windygoo** [comment]
> 谢谢！ 论文里PointNu-Net在CPM-17和kumar的结果是自己跑的实验吗

PointNu-Net论文有提供在Kumar上的结果，当前版本论文中（2024.1.8）其在CPM-17上的结果是我自己跑的，不过我前段时间找PointNu-Net的作者请他给自己的方法调了一下参数，结果稍有提高，之后会随着论文更新。

**Comment by wzr0108** [comment]
非常感谢！

**Comment by wzr0108** [comment]
期待开源

**Comment by windygoo** [comment]
> 期待开源

刚提交了一版arxiv，整理一下代码过两天就传上来。

**Comment by wzr0108** [comment]
![屏幕截图 2024-01-23 211807](https://github.com/windygoo/PromptNucSeg/assets/98294772/ed0e7fe9-e248-463a-bd50-d58affb1b598)
我只找到去年提交的论文

**Comment by windygoo** [comment]
> ![屏幕截图 2024-01-23 211807](https://private-user-images.githubusercontent.com/98294772/298953407-ed0e7fe9-e248-463a-bd50-d58affb1b598.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjMyMTUsIm5iZiI6MTcwNjAyMjkxNSwicGF0aCI6Ii85ODI5NDc3Mi8yOTg5NTM0MDctZWQwZTdmZTktZTI0OC00NjNhLWJkNTAtZDU4YWZmYjFiNTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE1MTUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MmQzNTdkOWEzZjBkYTBhN2ZhZjc4Yzk1MjlhMzYwNzI1NTc2Y2E0ZWJhNGEzYjY3YTc2MDQ3YTZmNGFhOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GeFWZ69NUXIhK8jsNeqeYfHEOCe0fal-n7QXjoCUpuo) 我只找到去年提交的论文

今天提交的，明天早上应该就出来了

**Comment by windygoo** [comment]
> 期待开源

你好，代码已上传。

**Comment by wzr0108** [comment]
非常感谢
