### ISSUE TITLE
图片大小的问题

### ISSUE THREAD

**Issue by wzr0108** [windygoo/PromptNucSeg#2]
作者您好，我在训练prompter的时候遇到这个问题
```
    return torch.stack(images), torch.stack(masks), points, labels
RuntimeError: stack expects each tensor to be equal size, but got [3, 512, 512] at entry 0 and [3, 608, 608] at entry 1
```
是两张图片的大小不一样导致的
我使用的是cpm17数据集，配置文件是prompter/config/cpm17.py。
cpm17的图片大小不一致，数据增强部分有pad，但是并没有pad到同一大小
```
train=dict(
        transform=[
            dict(type="RandomGridShuffle", grid=(4, 4), p=0.5),
            dict(
                type="ColorJitter",
                brightness=0.25,
                contrast=0.25,
                saturation=0.1,
                hue=0.05,
                p=0.2,
            ),
            dict(type="RandomRotate90", p=0.5),
            dict(type="Downscale", scale_max=0.5, scale_min=0.5, p=0.15),
            dict(type="Blur", blur_limit=10, p=0.2),
            dict(type="GaussNoise", var_limit=50, p=0.25),
            dict(type="ZoomBlur", p=0.1, max_factor=1.05),
            dict(type="HorizontalFlip", p=0.5),
            dict(type="VerticalFlip", p=0.5),
            dict(
                type="ShiftScaleRotate",
                shift_limit=0.3,
                scale_limit=0.1,
                rotate_limit=0,
                border_mode=0,
                value=0,
                p=0.5,
            ),
            dict(
                type="PadIfNeeded",
                min_height=None,
                min_width=None,
                pad_height_divisor=prompter["space"],
                pad_width_divisor=prompter["space"],
                position="top_left",
                p=1,
            ),
            dict(type="Normalize"),
        ]
    ),
```

**Comment by windygoo** [comment]
> 作者您好，我在训练prompter的时候遇到这个问题
> 
> ```
>     return torch.stack(images), torch.stack(masks), points, labels
> RuntimeError: stack expects each tensor to be equal size, but got [3, 512, 512] at entry 0 and [3, 608, 608] at entry 1
> ```
> 
> 是两张图片的大小不一样导致的 我使用的是cpm17数据集，配置文件是prompter/config/cpm17.py。 cpm17的图片大小不一致，数据增强部分有pad，但是并没有pad到同一大小
> 
> ```
> train=dict(
>         transform=[
>             dict(type="RandomGridShuffle", grid=(4, 4), p=0.5),
>             dict(
>                 type="ColorJitter",
>                 brightness=0.25,
>                 contrast=0.25,
>                 saturation=0.1,
>                 hue=0.05,
>                 p=0.2,
>             ),
>             dict(type="RandomRotate90", p=0.5),
>             dict(type="Downscale", scale_max=0.5, scale_min=0.5, p=0.15),
>             dict(type="Blur", blur_limit=10, p=0.2),
>             dict(type="GaussNoise", var_limit=50, p=0.25),
>             dict(type="ZoomBlur", p=0.1, max_factor=1.05),
>             dict(type="HorizontalFlip", p=0.5),
>             dict(type="VerticalFlip", p=0.5),
>             dict(
>                 type="ShiftScaleRotate",
>                 shift_limit=0.3,
>                 scale_limit=0.1,
>                 rotate_limit=0,
>                 border_mode=0,
>                 value=0,
>                 p=0.5,
>             ),
>             dict(
>                 type="PadIfNeeded",
>                 min_height=None,
>                 min_width=None,
>                 pad_height_divisor=prompter["space"],
>                 pad_width_divisor=prompter["space"],
>                 position="top_left",
>                 p=1,
>             ),
>             dict(type="Normalize"),
>         ]
>     ),
> ```

我更新了下config文件，应该可以了。

**Comment by wzr0108** [comment]
![屏幕截图 2024-01-30 163053](https://github.com/windygoo/PromptNucSeg/assets/98294772/8b8ca3a2-cb30-4335-ab45-1065830f5534)
这个loss是正常的吗

**Comment by windygoo** [comment]
> ![屏幕截图 2024-01-30 163053](https://private-user-images.githubusercontent.com/98294772/300732561-8b8ca3a2-cb30-4335-ab45-1065830f5534.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MDQwMjMsIm5iZiI6MTcwNjYwMzcyMywicGF0aCI6Ii85ODI5NDc3Mi8zMDA3MzI1NjEtOGI4Y2EzYTItY2IzMC00MzM1LWFiNDUtMTA2NTgzMGY1NTM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA4MzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NTEwZGQxMmI4MDU5MDU3Zjc4ZjFhMjJlYTlhODk2ZGVlMGRiMTljYWY2ZTZkNjE0ZGI5YTIyYjIyNTM3YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pP4XPNyBvF4egO4qBijs7tJXNo-pylPN70XX7ZN7p8M) 这个loss是正常的吗

不正常，重新拉一下prompter/dataset.py

**Comment by windygoo** [comment]
你加我qq吧, 1373697070

**Comment by wzr0108** [comment]
这个qq号搜不到啊

**Comment by wzr0108** [comment]
![image](https://github.com/windygoo/PromptNucSeg/assets/98294772/644676c4-d77b-4b92-8575-aaf2a96e2ae3)

**Comment by windygoo** [comment]
> 这个qq号搜不到啊

你再试试？
