### ISSUE TITLE
关于预训练权重

### ISSUE THREAD

**Issue by lavainhat** [windygoo/PromptNucSeg#7]
kumar的预训练权重中没有"optimizer"和"epoch"这两个键，我直接注释掉main中的        optimizer.load_state_dict(checkpoint["optimizer"])
        args.start_epoch = checkpoint["epoch"] + 1
来在kumar预训练权重的基础上用自己数据集来训练这是对的吗？
![image](https://github.com/user-attachments/assets/3bebc77e-fac0-4d84-a0c5-e18d558e83e7)

**Comment by windygoo** [comment]
> kumar的预训练权重中没有"optimizer"和"epoch"这两个键，我直接注释掉main中的 optimizer.load_state_dict(checkpoint["optimizer"]) args.start_epoch = checkpoint["epoch"] + 1 来在kumar预训练权重的基础上用自己数据集来训练这是对的吗？ ![image](https://private-user-images.githubusercontent.com/99528460/388141775-3bebc77e-fac0-4d84-a0c5-e18d558e83e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MjY5MTQsIm5iZiI6MTczMjYyNjYxNCwicGF0aCI6Ii85OTUyODQ2MC8zODgxNDE3NzUtM2JlYmM3N2UtZmFjMC00ZDg0LWEwYzUtZTE4ZDU1OGU4M2U3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDEzMTAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlOWE5MmZhMDAwOWUwYTE1M2FmZjRhOTY0MDE4YmQ5NTM0ZDRkMTU3Y2I4MmM5ZTZjNmJlZGM2ZTgzMjM1MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.08UN5CgmKofycRIzfvOG0xwFI0XH_3d2Er7a_0ej_hk)

没问题的
